runtime: python
env: flex
entrypoint: gunicorn -b :$PORT ShoppingSite.wsgi

beta_settings:
  cloud_sql_instances: shopping-deploy:us-central1:shopping-site

env_variables:
  DJANGO_SETTINGS_MODULE: ShoppingSite.production_setting
  GOOGLE_APPLICATION_CREDENTIALS: SHOPPING DEPLOY-2f2a1339c178.json

runtime_config:
  python_version: 3