# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180211_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='country',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='postal_code',
            field=models.CharField(default='', max_length=16),
        ),
    ]
