# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180212_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='address',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='address1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='address2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
