# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 20:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_auto_20180218_0410'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0004_auto_20180212_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_full_name', models.CharField(default='', max_length=100, null=True)),
                ('shipping_postal_code', models.CharField(default='', max_length=16, null=True)),
                ('shipping_country', models.CharField(choices=[('China', 'China'), ('Canada', 'Canada'), ('Japan', 'Japan'), ('United Kingdom', 'United Kingdom'), ('United States', 'United States'), ('Taiwan', 'Taiwan')], max_length=50, null=True)),
                ('shipping_address1', models.CharField(default='', max_length=100, null=True)),
                ('shipping_address2', models.CharField(default='', max_length=100, null=True)),
                ('shipping_phone_number', models.CharField(default='', max_length=15, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='accounts.UserAddress')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='carts.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
