# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180218_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star_rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
